### ISSUE TITLE
Redux Setup

### ISSUE THREAD

**Issue by geofflin** [cipherchase/cipherchase#10]
- [x] Create boilerplate for actionCreators.js and actions.js (action types)
 - [x] Add reducers, store and boilerplate js files
 - [x] Installed redux libraries
 - [x] Wrapped ```<Main Container />``` component with ```<Provider />``` component
 - [x] Test Redux store is connected correctly with React components using mock state data
