### ISSUE TITLE
Create server route and logic for /signup

### ISSUE THREAD

**Issue by geofflin** [cipherchase/cipherchase#13]
### Tasks
 - [x] Setup server route handler for signup post request
 - [x] Validate unique email
 - [x] Application should post user credentials to database
