### ISSUE TITLE
Move user car based on key press when game starts

### ISSUE THREAD

**Issue by geofflin** [cipherchase/cipherchase#19]
As an end user, I should be able to play the game after clicking start. I should see the User car move after typing in the code correctly. 

### Tasks
 - [x] On successful keypress, car should move 
 - [x] On unsuccessful keypress, car should not move and visual cursor should display on the code to indicate bad keypress (e.g. red text)
 - [x] Timer should increment until game ends
