### ISSUE TITLE
Create endgame UI

### ISSUE THREAD

**Issue by geofflin** [cipherchase/cipherchase#21]
As a user, when either the User or CPU car reaches the finish line, I should see a message indicating the game is over. Cars should stop

### Tasks
 - [x] Message display for win and lose conditions (e.g. "You Win!" / "You Lose")
 - [x] All cars should stop moving
 - [x] Score should increment on win condition
