### ISSUE TITLE
Create database schema tables

### ISSUE THREAD

**Issue by geofflin** [cipherchase/cipherchase#24]
- [x] Create 'Users' table with following fields:
    - id
    - email
    - first name
    - last name
    - password
    - score
 - [x] Create 'Code_Challenges" table with following fields:
    - id
    - challenge
 - [x] Create .sql file
 - [x] Populate tables with mock data
