### ISSUE TITLE
PostgreSQL DB Setup

### ISSUE THREAD

**Issue by geofflin** [cipherchase/cipherchase#8]
- [x] Installed dependencies (dotenv, pg) in package.json
 - [x] Created db folder at root level directory
 - [x] Created psqlPool.js file to connect to PostgreSQL database for both production and development based on node environment variable mode
