### ISSUE TITLE
React Setup

### ISSUE THREAD

**Issue by geofflin** [cipherchase/cipherchase#9]
- [x] Add dependencies for React and Webpack
 - [x] Add index.js
 - [x] Add App.jsx
 - [x] Add webpack.config
 - [x] Add index.html
 - [x] Add MainContainer.jsx
